project:
  type: website
  output-dir: C:/Users/clarigtz.stu/OneDrive - UBC/Documents/GitHub/E-Portfolio

website:
  title: "E-Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: work.qmd
        text: Map Gallery
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: sandstone
    css: custom.css
    toc: true

editor: visual

