---
title: "Resume"
format: html
editor: visual
---

# **Education**

**Master of Geomatics for Environmental Management**\
University of British Columbia\
2025 - Present

**B.Eng. Environmental Sciences** \
Sonora Institute of Technology\
2018 - 2022

## **Work Experience**

**Graduate Research Assistant \
**University of British Columbia, Faculty of Arts\
Collaborative Digital Heritage Studio\
Vancouver, Canada\
2025 - Present

-   Developed interactive web mapping experiences (ArcGIS Experience Builder, StoryMaps) for Indigenous cultural preservation and storytelling.

<!-- -->

-    Translated research into accessible, public-facing content through cross-team collaboration.

**Project Manager\
**642 Studio, Digital Marketing & SAAS\
Sonora, Mexico\
2024-2025

-   Coordinated concurrent client projects, managing scope, timelines, deliverables, and documentation.

<!-- -->

-    Liaised across clients, vendors, and internal teams, providing updates and supporting QA to keep delivery on track.

**Undergraduate Research Assistant\
**Sonora Institute of Technology\
Water and Environmental Sciences Department\
Sonora, Mexico\
2021-2022

-   Supported climate impacts research via data collection, dataset management, and reproducible statistical analysis in R.

<!-- -->

-    Analyzed 400+ wheat leaf imprint samples and contributed to literature review and technical writing.

**Environmental Intern Lead\
**Rubisco, Environmental Solutions Consulting\
Sonora, Mexico\
2020-2021

-   Directed a 4-person project delivering GIS and remote sensing analysis of illegal waste disposal impacts to inform sustainability planning.

<!-- -->

-    Produced georeferenced high-tension tower locations, interpreted UAV-based observations to support infrastructure condition reporting and risk documentation.

##  Conferences 

**1st International Congress of Agroecosystems** \
Stomatal Characterization of the Durum Wheat Variety CIRNO C2008 in the Yaqui Valley under Elevated Night Temperature Conditions\
Poster Presentation\
2021\
\

## Scholarships 

**2025 Excellence Scholarship for Graduate Studies Abroad**\
Esposos Rodríguez Foundation\
\$32,000 USD\
\

## Institutional Service

**2nd International Conference on Forest Therapy\
**Logistics Volunteer\
Vancouver, Canada\
2025

**6th International Symposium on Environmental Biotechnology and Engineering\
**Volunteer\
Sonora, Mexico\
2018
